# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2861c30d52cd56637f15c88dfc7715105f730f63e7aa652634a6937326b2df5d26074b30adb9e8af9df3539e7dd2464071a20266c4206e5341d804485cde237a

test:
  secret_key_base: 3efdaf2bafd8e8911cd00e863b120f9bf30b89cb570a2b4c372254175fd379c87245218d300ff043eeb096be25ba709325deec2b02415f285e14d38e0b9a787a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
